version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: kgc-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kgcuration
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "admin", "-proot", "-e", "SELECT 1"]
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./knowledge-graph-curation-api
      dockerfile: Dockerfile
    container_name: kgc-django-backend
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./knowledge-graph-curation-api:/app
    ports:
      - "8000:8000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 2048M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=kgcuration
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=root
      - DATABASE_PORT=3306
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build:
      context: ./knowledge-graph-curation
      dockerfile: Dockerfile
    container_name: kgc-vuejs-frontend
    restart: always
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - ./knowledge-graph-curation:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
