name: Knowledge Graph Curation Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Docker Image
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/billgates98/knowledge-graph-curation:latest
            ghcr.io/billgates98/knowledge-graph-curation:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/billgates98/knowledge-graph-curation
            org.opencontainers.image.description="Vue version of Knowledge Graph Curation"
            org.opencontainers.image.version=1.0.0
            org.opencontainers.image.authors="Bill Gates Happi Happi, PhD"
            org.opencontainers.image.licenses=MIT

      - name: Image Digest
        if: steps.docker-build-push.outputs.digest
        run: echo "Image digest "

    
    

